language: python
python:
  - "3.9"

install:
  - pip install -r requirements.txt

script:
  - cd $TRAVIS_BUILD_DIR/luki_modern_robotics && pylint **/*.py
  - cd $TRAVIS_BUILD_DIR/luki_modern_robotics/test && pytest
  - cd $TRAVIS_BUILD_DIR/luki_modern_robotics/ && coverage run --omit="*/virtualenv/*" -m pytest && coverage report
